// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/opencloud-eu/opencloud/services/guestauth/pkg/service/token"
	mock "github.com/stretchr/testify/mock"
)

// NewGuestAuth creates a new instance of GuestAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGuestAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *GuestAuth {
	mock := &GuestAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GuestAuth is an autogenerated mock type for the GuestAuth type
type GuestAuth struct {
	mock.Mock
}

type GuestAuth_Expecter struct {
	mock *mock.Mock
}

func (_m *GuestAuth) EXPECT() *GuestAuth_Expecter {
	return &GuestAuth_Expecter{mock: &_m.Mock}
}

// CleanupShare provides a mock function for the type GuestAuth
func (_mock *GuestAuth) CleanupShare(shareID string) error {
	ret := _mock.Called(shareID)

	if len(ret) == 0 {
		panic("no return value specified for CleanupShare")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(shareID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// GuestAuth_CleanupShare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupShare'
type GuestAuth_CleanupShare_Call struct {
	*mock.Call
}

// CleanupShare is a helper method to define mock.On call
//   - shareID string
func (_e *GuestAuth_Expecter) CleanupShare(shareID any) *GuestAuth_CleanupShare_Call {
	return &GuestAuth_CleanupShare_Call{Call: _e.mock.On("CleanupShare", shareID)}
}

func (_c *GuestAuth_CleanupShare_Call) Run(run func(shareID string)) *GuestAuth_CleanupShare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *GuestAuth_CleanupShare_Call) Return(err error) *GuestAuth_CleanupShare_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *GuestAuth_CleanupShare_Call) RunAndReturn(run func(shareID string) error) *GuestAuth_CleanupShare_Call {
	_c.Call.Return(run)
	return _c
}

// CreateToken provides a mock function for the type GuestAuth
func (_mock *GuestAuth) CreateToken(ctx context.Context, shareID string) (*token.Token, error) {
	ret := _mock.Called(ctx, shareID)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 *token.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*token.Token, error)); ok {
		return returnFunc(ctx, shareID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *token.Token); ok {
		r0 = returnFunc(ctx, shareID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, shareID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GuestAuth_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type GuestAuth_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - shareID string
func (_e *GuestAuth_Expecter) CreateToken(ctx any, shareID any) *GuestAuth_CreateToken_Call {
	return &GuestAuth_CreateToken_Call{Call: _e.mock.On("CreateToken", ctx, shareID)}
}

func (_c *GuestAuth_CreateToken_Call) Run(run func(ctx context.Context, shareID string)) *GuestAuth_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GuestAuth_CreateToken_Call) Return(token1 *token.Token, err error) *GuestAuth_CreateToken_Call {
	_c.Call.Return(token1, err)
	return _c
}

func (_c *GuestAuth_CreateToken_Call) RunAndReturn(run func(ctx context.Context, shareID string) (*token.Token, error)) *GuestAuth_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}

// Redeem provides a mock function for the type GuestAuth
func (_mock *GuestAuth) Redeem(ctx context.Context, tokenString string) (string, error) {
	ret := _mock.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for Redeem")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, tokenString)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GuestAuth_Redeem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Redeem'
type GuestAuth_Redeem_Call struct {
	*mock.Call
}

// Redeem is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *GuestAuth_Expecter) Redeem(ctx any, tokenString any) *GuestAuth_Redeem_Call {
	return &GuestAuth_Redeem_Call{Call: _e.mock.On("Redeem", ctx, tokenString)}
}

func (_c *GuestAuth_Redeem_Call) Run(run func(ctx context.Context, tokenString string)) *GuestAuth_Redeem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GuestAuth_Redeem_Call) Return(s string, err error) *GuestAuth_Redeem_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *GuestAuth_Redeem_Call) RunAndReturn(run func(ctx context.Context, tokenString string) (string, error)) *GuestAuth_Redeem_Call {
	_c.Call.Return(run)
	return _c
}
