// Code generated by gowrap. DO NOT EDIT.
// template: ldap_client_goldap.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package identity

import (
	"github.com/go-ldap/ldap/v3"
)

// implementation that adapts the go-ldap ldap.Client interface
// and delegates everything to a proper LDAP client
type GoLdapLdapClient struct {
	delegate ldap.Client
}

var _ LdapClient = &GoLdapLdapClient{}

func NewGoLdapLdapClient(delegate ldap.Client) *GoLdapLdapClient {
	return &GoLdapLdapClient{delegate: delegate}
}

// Add implements LdapClient.Add
// and delegates to ldap.Client.Add
func (_d GoLdapLdapClient) Add(ap1 *ldap.AddRequest) (err error) {
	return _d.delegate.Add(ap1)
}

// Del implements LdapClient.Del
// and delegates to ldap.Client.Del
func (_d GoLdapLdapClient) Del(dp1 *ldap.DelRequest) (err error) {
	return _d.delegate.Del(dp1)
}

// Modify implements LdapClient.Modify
// and delegates to ldap.Client.Modify
func (_d GoLdapLdapClient) Modify(mp1 *ldap.ModifyRequest) (err error) {
	return _d.delegate.Modify(mp1)
}

// ModifyDN implements LdapClient.ModifyDN
// and delegates to ldap.Client.ModifyDN
func (_d GoLdapLdapClient) ModifyDN(mp1 *ldap.ModifyDNRequest) (err error) {
	return _d.delegate.ModifyDN(mp1)
}

// PasswordModify implements LdapClient.PasswordModify
// and delegates to ldap.Client.PasswordModify
func (_d GoLdapLdapClient) PasswordModify(pp1 *ldap.PasswordModifyRequest) (pp2 *ldap.PasswordModifyResult, err error) {
	return _d.delegate.PasswordModify(pp1)
}

// Search implements LdapClient.Search
// and delegates to ldap.Client.Search
func (_d GoLdapLdapClient) Search(sp1 *ldap.SearchRequest) (sp2 *ldap.SearchResult, err error) {
	return _d.delegate.Search(sp1)
}
