// Code generated by gowrap. DO NOT EDIT.
// template: ldap_client_prometheus.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package identity

import (
	"errors"
	"sync/atomic"
	"time"

	"github.com/go-ldap/ldap/v3"
	"github.com/opencloud-eu/opencloud/services/graph/pkg/metrics"
	"github.com/prometheus/client_golang/prometheus"
)

// PrometheusLdapClient implements LdapClient interface with all methods wrapped
// with Prometheus metrics
type PrometheusLdapClient struct {
	delegate LdapClient
	timer    *prometheus.HistogramVec
	inflight *atomic.Int64
}

var _ LdapClient = &PrometheusLdapClient{}

// returns an instance of the LdapClient decorated with prometheus metric
func NewPrometheusLdapClient(delegate LdapClient, timer *prometheus.HistogramVec, inflight *atomic.Int64) PrometheusLdapClient {
	return PrometheusLdapClient{
		delegate: delegate,
		timer:    timer,
		inflight: inflight,
	}
}

// Add implements LdapClient.Add
func (_d PrometheusLdapClient) Add(ap1 *ldap.AddRequest) (err error) {
	_d.inflight.Add(1)
	defer _d.inflight.Add(-1)

	_since := time.Now()
	defer func() {
		duration := time.Since(_since).Seconds()
		result := metrics.ResultSuccess
		if err != nil {
			if err == ErrReadOnly {
				result = metrics.ResultReadOnly
			} else {
				result = metrics.ResultFailure
				var lerr *ldap.Error
				if errors.As(err, &lerr) {
					if lerr != nil && lerr.ResultCode == ldap.LDAPResultNoSuchObject {
						result = metrics.ResultNotFound
					}
				}
			}
		}

		_d.timer.WithLabelValues(LdapOpAdd, result).Observe(duration)
	}()

	return _d.delegate.Add(ap1)
}

// Del implements LdapClient.Del
func (_d PrometheusLdapClient) Del(dp1 *ldap.DelRequest) (err error) {
	_d.inflight.Add(1)
	defer _d.inflight.Add(-1)

	_since := time.Now()
	defer func() {
		duration := time.Since(_since).Seconds()
		result := metrics.ResultSuccess
		if err != nil {
			if err == ErrReadOnly {
				result = metrics.ResultReadOnly
			} else {
				result = metrics.ResultFailure
				var lerr *ldap.Error
				if errors.As(err, &lerr) {
					if lerr != nil && lerr.ResultCode == ldap.LDAPResultNoSuchObject {
						result = metrics.ResultNotFound
					}
				}
			}
		}

		_d.timer.WithLabelValues(LdapOpDel, result).Observe(duration)
	}()

	return _d.delegate.Del(dp1)
}

// Modify implements LdapClient.Modify
func (_d PrometheusLdapClient) Modify(mp1 *ldap.ModifyRequest) (err error) {
	_d.inflight.Add(1)
	defer _d.inflight.Add(-1)

	_since := time.Now()
	defer func() {
		duration := time.Since(_since).Seconds()
		result := metrics.ResultSuccess
		if err != nil {
			if err == ErrReadOnly {
				result = metrics.ResultReadOnly
			} else {
				result = metrics.ResultFailure
				var lerr *ldap.Error
				if errors.As(err, &lerr) {
					if lerr != nil && lerr.ResultCode == ldap.LDAPResultNoSuchObject {
						result = metrics.ResultNotFound
					}
				}
			}
		}

		_d.timer.WithLabelValues(LdapOpModify, result).Observe(duration)
	}()

	return _d.delegate.Modify(mp1)
}

// ModifyDN implements LdapClient.ModifyDN
func (_d PrometheusLdapClient) ModifyDN(mp1 *ldap.ModifyDNRequest) (err error) {
	_d.inflight.Add(1)
	defer _d.inflight.Add(-1)

	_since := time.Now()
	defer func() {
		duration := time.Since(_since).Seconds()
		result := metrics.ResultSuccess
		if err != nil {
			if err == ErrReadOnly {
				result = metrics.ResultReadOnly
			} else {
				result = metrics.ResultFailure
				var lerr *ldap.Error
				if errors.As(err, &lerr) {
					if lerr != nil && lerr.ResultCode == ldap.LDAPResultNoSuchObject {
						result = metrics.ResultNotFound
					}
				}
			}
		}

		_d.timer.WithLabelValues(LdapOpModifyDN, result).Observe(duration)
	}()

	return _d.delegate.ModifyDN(mp1)
}

// PasswordModify implements LdapClient.PasswordModify
func (_d PrometheusLdapClient) PasswordModify(pp1 *ldap.PasswordModifyRequest) (pp2 *ldap.PasswordModifyResult, err error) {
	_d.inflight.Add(1)
	defer _d.inflight.Add(-1)

	_since := time.Now()
	defer func() {
		duration := time.Since(_since).Seconds()
		result := metrics.ResultSuccess
		if err != nil {
			if err == ErrReadOnly {
				result = metrics.ResultReadOnly
			} else {
				result = metrics.ResultFailure
				var lerr *ldap.Error
				if errors.As(err, &lerr) {
					if lerr != nil && lerr.ResultCode == ldap.LDAPResultNoSuchObject {
						result = metrics.ResultNotFound
					}
				}
			}
		}

		_d.timer.WithLabelValues(LdapOpPasswordModify, result).Observe(duration)
	}()

	return _d.delegate.PasswordModify(pp1)
}

// Search implements LdapClient.Search
func (_d PrometheusLdapClient) Search(sp1 *ldap.SearchRequest) (sp2 *ldap.SearchResult, err error) {
	_d.inflight.Add(1)
	defer _d.inflight.Add(-1)

	_since := time.Now()
	defer func() {
		duration := time.Since(_since).Seconds()
		result := metrics.ResultSuccess
		if err != nil {
			if err == ErrReadOnly {
				result = metrics.ResultReadOnly
			} else {
				result = metrics.ResultFailure
				var lerr *ldap.Error
				if errors.As(err, &lerr) {
					if lerr != nil && lerr.ResultCode == ldap.LDAPResultNoSuchObject {
						result = metrics.ResultNotFound
					}
				}
			}
		}

		_d.timer.WithLabelValues(LdapOpSearch, result).Observe(duration)
	}()

	return _d.delegate.Search(sp1)
}
