// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/opencloud-eu/opencloud/services/auth-guest/pkg/service/authguest"
	"github.com/opencloud-eu/opencloud/services/auth-guest/pkg/service/token"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthGuest creates a new instance of AuthGuest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthGuest(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthGuest {
	mock := &AuthGuest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthGuest is an autogenerated mock type for the AuthGuest type
type AuthGuest struct {
	mock.Mock
}

type AuthGuest_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthGuest) EXPECT() *AuthGuest_Expecter {
	return &AuthGuest_Expecter{mock: &_m.Mock}
}

// CleanupShare provides a mock function for the type AuthGuest
func (_mock *AuthGuest) CleanupShare(shareID string) error {
	ret := _mock.Called(shareID)

	if len(ret) == 0 {
		panic("no return value specified for CleanupShare")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(shareID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthGuest_CleanupShare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupShare'
type AuthGuest_CleanupShare_Call struct {
	*mock.Call
}

// CleanupShare is a helper method to define mock.On call
//   - shareID string
func (_e *AuthGuest_Expecter) CleanupShare(shareID any) *AuthGuest_CleanupShare_Call {
	return &AuthGuest_CleanupShare_Call{Call: _e.mock.On("CleanupShare", shareID)}
}

func (_c *AuthGuest_CleanupShare_Call) Run(run func(shareID string)) *AuthGuest_CleanupShare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthGuest_CleanupShare_Call) Return(err error) *AuthGuest_CleanupShare_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthGuest_CleanupShare_Call) RunAndReturn(run func(shareID string) error) *AuthGuest_CleanupShare_Call {
	_c.Call.Return(run)
	return _c
}

// CreateToken provides a mock function for the type AuthGuest
func (_mock *AuthGuest) CreateToken(ctx context.Context, shareID string) (*token.Token, error) {
	ret := _mock.Called(ctx, shareID)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 *token.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*token.Token, error)); ok {
		return returnFunc(ctx, shareID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *token.Token); ok {
		r0 = returnFunc(ctx, shareID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, shareID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthGuest_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type AuthGuest_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - shareID string
func (_e *AuthGuest_Expecter) CreateToken(ctx any, shareID any) *AuthGuest_CreateToken_Call {
	return &AuthGuest_CreateToken_Call{Call: _e.mock.On("CreateToken", ctx, shareID)}
}

func (_c *AuthGuest_CreateToken_Call) Run(run func(ctx context.Context, shareID string)) *AuthGuest_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthGuest_CreateToken_Call) Return(token1 *token.Token, err error) *AuthGuest_CreateToken_Call {
	_c.Call.Return(token1, err)
	return _c
}

func (_c *AuthGuest_CreateToken_Call) RunAndReturn(run func(ctx context.Context, shareID string) (*token.Token, error)) *AuthGuest_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}

// Redeem provides a mock function for the type AuthGuest
func (_mock *AuthGuest) Redeem(ctx context.Context, tokenString string) (*authguest.RedeemResponse, error) {
	ret := _mock.Called(ctx, tokenString)

	if len(ret) == 0 {
		panic("no return value specified for Redeem")
	}

	var r0 *authguest.RedeemResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*authguest.RedeemResponse, error)); ok {
		return returnFunc(ctx, tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *authguest.RedeemResponse); ok {
		r0 = returnFunc(ctx, tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authguest.RedeemResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthGuest_Redeem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Redeem'
type AuthGuest_Redeem_Call struct {
	*mock.Call
}

// Redeem is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenString string
func (_e *AuthGuest_Expecter) Redeem(ctx any, tokenString any) *AuthGuest_Redeem_Call {
	return &AuthGuest_Redeem_Call{Call: _e.mock.On("Redeem", ctx, tokenString)}
}

func (_c *AuthGuest_Redeem_Call) Run(run func(ctx context.Context, tokenString string)) *AuthGuest_Redeem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthGuest_Redeem_Call) Return(redeemResponse *authguest.RedeemResponse, err error) *AuthGuest_Redeem_Call {
	_c.Call.Return(redeemResponse, err)
	return _c
}

func (_c *AuthGuest_Redeem_Call) RunAndReturn(run func(ctx context.Context, tokenString string) (*authguest.RedeemResponse, error)) *AuthGuest_Redeem_Call {
	_c.Call.Return(run)
	return _c
}
