with-expecter: true
filename: "{{.InterfaceName | snakecase }}.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
    github.com/opencloud-eu/opencloud/protogen/gen/opencloud/services/eventhistory/v0:
        interfaces:
            EventHistoryService:
    github.com/opencloud-eu/opencloud/protogen/gen/opencloud/services/policies/v0:
        interfaces:
            PoliciesProviderService:
    github.com/opencloud-eu/opencloud/protogen/gen/opencloud/services/search/v0:
        interfaces:
            SearchProviderService:
    github.com/opencloud-eu/opencloud/protogen/gen/opencloud/services/settings/v0:
        interfaces:
            ValueService:
    github.com/opencloud-eu/opencloud/protogen/gen/opencloud/services/thumbnails/v0:
        interfaces:
            ThumbnailService:
