// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/opencloud-eu/opencloud/services/guestauth/pkg/service/storage"
	mock "github.com/stretchr/testify/mock"
)

// NewManager creates a new instance of Manager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Manager {
	mock := &Manager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

type Manager_Expecter struct {
	mock *mock.Mock
}

func (_m *Manager) EXPECT() *Manager_Expecter {
	return &Manager_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type Manager
func (_mock *Manager) Add(rec storage.Record) error {
	ret := _mock.Called(rec)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(storage.Record) error); ok {
		r0 = returnFunc(rec)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Manager_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type Manager_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - rec storage.Record
func (_e *Manager_Expecter) Add(rec any) *Manager_Add_Call {
	return &Manager_Add_Call{Call: _e.mock.On("Add", rec)}
}

func (_c *Manager_Add_Call) Run(run func(rec storage.Record)) *Manager_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 storage.Record
		if args[0] != nil {
			arg0 = args[0].(storage.Record)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Manager_Add_Call) Return(err error) *Manager_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Manager_Add_Call) RunAndReturn(run func(rec storage.Record) error) *Manager_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type Manager
func (_mock *Manager) Get(shareIDHash string) (storage.Record, error) {
	ret := _mock.Called(shareIDHash)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 storage.Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (storage.Record, error)); ok {
		return returnFunc(shareIDHash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) storage.Record); ok {
		r0 = returnFunc(shareIDHash)
	} else {
		r0 = ret.Get(0).(storage.Record)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(shareIDHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Manager_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Manager_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - shareIDHash string
func (_e *Manager_Expecter) Get(shareIDHash any) *Manager_Get_Call {
	return &Manager_Get_Call{Call: _e.mock.On("Get", shareIDHash)}
}

func (_c *Manager_Get_Call) Run(run func(shareIDHash string)) *Manager_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Manager_Get_Call) Return(record storage.Record, err error) *Manager_Get_Call {
	_c.Call.Return(record, err)
	return _c
}

func (_c *Manager_Get_Call) RunAndReturn(run func(shareIDHash string) (storage.Record, error)) *Manager_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Redeem provides a mock function for the type Manager
func (_mock *Manager) Redeem(shareIDHash string) error {
	ret := _mock.Called(shareIDHash)

	if len(ret) == 0 {
		panic("no return value specified for Redeem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(shareIDHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Manager_Redeem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Redeem'
type Manager_Redeem_Call struct {
	*mock.Call
}

// Redeem is a helper method to define mock.On call
//   - shareIDHash string
func (_e *Manager_Expecter) Redeem(shareIDHash any) *Manager_Redeem_Call {
	return &Manager_Redeem_Call{Call: _e.mock.On("Redeem", shareIDHash)}
}

func (_c *Manager_Redeem_Call) Run(run func(shareIDHash string)) *Manager_Redeem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Manager_Redeem_Call) Return(err error) *Manager_Redeem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Manager_Redeem_Call) RunAndReturn(run func(shareIDHash string) error) *Manager_Redeem_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type Manager
func (_mock *Manager) Remove(shareIDHash string) error {
	ret := _mock.Called(shareIDHash)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(shareIDHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Manager_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type Manager_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - shareIDHash string
func (_e *Manager_Expecter) Remove(shareIDHash any) *Manager_Remove_Call {
	return &Manager_Remove_Call{Call: _e.mock.On("Remove", shareIDHash)}
}

func (_c *Manager_Remove_Call) Run(run func(shareIDHash string)) *Manager_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Manager_Remove_Call) Return(err error) *Manager_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Manager_Remove_Call) RunAndReturn(run func(shareIDHash string) error) *Manager_Remove_Call {
	_c.Call.Return(run)
	return _c
}
